# Generated by Django 4.2.6 on 2023-12-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('Empno', models.IntegerField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=50)),
                ('Job', models.CharField(max_length=20)),
                ('Mgr', models.IntegerField()),
                ('Hire_Date', models.DateField()),
                ('Sal', models.IntegerField()),
                ('Comm', models.IntegerField()),
                ('Dept_No', models.IntegerField()),
            ],
        ),
    ]
