# Generated by Django 4.2.6 on 2023-12-08 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Name', models.CharField(max_length=20)),
                ('Loc', models.CharField(max_length=30)),
                ('Dept_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employeetable')),
            ],
        ),
        migrations.CreateModel(
            name='SalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.IntegerField()),
                ('Losal', models.IntegerField()),
                ('Hisal', models.IntegerField()),
                ('Loc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.dept')),
            ],
        ),
    ]
